version: "3.7"
services:
  postgres:
    image: postgres:16.9
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=user-service
